= Лабораторная работа 15

== Задание на уровень A

=== Описание задачи

Создайте класс SourceScannerA с методом main, который читает все файлы *.java из
каталога src и его подкаталогов.

Каталог можно получить так:

  String src = System.getProperty("user.dir") + File.separator + "src" + File.separator;

Файлы, содержащие в тексте @Test или org.junit.Test (тесты) не участвуют в
обработке.

В каждом тексте файла необходимо:

. Удалить строку package и все импорты за O(n).
. Удалить все символы с кодом <33 в начале и конце текстов.

В полученном наборе текстов:

. Рассчитать размер в байтах для полученных текстов и вывести в консоль размер и
относительный от src путь к каждому из файлов (по одному в строке)

. При выводе сортировать файлы по размеру, а если размер одинаковый, то
лексикографически сортировать пути

Найдите способ игнорировать ошибки MalformedInputException

Все операции не должны ничего менять на дисках (разрешено только чтение) Работа
не имеет цели найти плагиат, поэтому не нужно менять коды своих программ.

== Задание на уровень B

=== Описание задачи

Создайте класс SourceScannerB с методом main, который читает все файлы *.java из
каталога src и его подкаталогов.

Каталог можно получить так:

  String src = System.getProperty("user.dir") + File.separator + "src" + File.separator;

Файлы, содержащие в тексте @Test или org.junit.Test (тесты) не участвуют в
обработке.

В каждом тексте файла необходимо:

. Удалить строку package и все импорты за O(n) от длины текста.
. Удалить все комментарии за O(n) от длины текста.
. Удалить все символы с кодом <33 в начале и конце текстов.
. Удалить пустые строки

В полученном наборе текстов:

. Рассчитать размер в байтах для полученных текстов и вывести в консоль размер и
относительный от src путь к каждому из файлов (по одному в строке)

. При выводе сортировать файлы по размеру, а если размер одинаковый, то
лексикографически сортировать пути

Найдите способ корректно обрабатывать ошибки MalformedInputException

Все операции не должны ничего менять на дисках (разрешено только чтение) Работа
не имеет цели найти плагиат, поэтому не нужно менять коды своих программ.

== Задание на уровень C

=== Описание задачи

Создайте класс SourceScannerC с методом main, который читает все файлы *.java из
каталога src и его подкаталогов.

Каталог можно получить так:

  String src = System.getProperty("user.dir") + File.separator + "src" + File.separator;

Файлы, содержащие в тексте @Test или org.junit.Test (тесты) не участвуют в
обработке.

В каждом тексте файла необходимо:

. Удалить строку package и все импорты.
. Удалить все комментарии за O(n) от длины текста.
. Заменить все последовательности символов с кодом <33 на 32 (пробел).

В полученном наборе текстов:

. Найти наиболее похожие тексты по метрике "расстояние Левенштейна", и
определить копия ли это, считая копиями файлы с числом правок <10.

. Если файл имеет копию или копии, то вывести путь файла и в следующих строках
путь(и) к копии(ям).

. Повторить для всех файлов с копиями, при выводе сортировать файлы
лексикографически по их пути.

Найдите способ корректно обрабатывать ошибки MalformedInputException

Оптимизируйте производительность решения (это может интересно).

Все операции не должны ничего менять на дисках (разрешено только чтение). Работа
не имеет цели найти плагиат, поэтому не нужно менять коды своих программ.

