= Лабораторная работа 11

== Задание на уровень А

Создайте class MyHashSet<E>, который реализует интерфейс Set<E> и работает на
основе массива с адресацией по хеш-коду и односвязным списком для элементов с
коллизиями БЕЗ использования других классов СТАНДАРТНОЙ БИБЛИОТЕКИ.

Метод toString() может выводить элементы в произвольном порядке Формат вывода:
скобки (квадратные) и разделитель (запятая с пробелом) должны быть такими же как
в методе toString() обычной коллекции.

Обязательные к реализации методы::
. size()
. clear()
. isEmpty()
. add(Object)
. remove(Object)
. contains(Object)

== Задание на уровень B

Создайте class MyLinkedHashSet<E>, который реализует интерфейс Set<E> и работает
на основе массива с адресацией по хеш-коду и односвязным списком для элементов с
коллизиями БЕЗ использования других классов СТАНДАРТНОЙ БИБЛИОТЕКИ.

Метод toString() должен выводить элементы в порядке их добавления в коллекцию
Формат вывода: скобки (квадратные) и разделитель (запятая с пробелом) должны
быть такими же как в методе toString() обычной коллекции.

Обязательные к реализации методы::
. toString()
. size()
. clear()
. isEmpty()
. add(Object)
. remove(Object)
. contains(Object)
. containsAll(Collection)
. addAll(Collection)
. removeAll(Collection)
. retainAll(Collection)

== Задание на уровень C

Создайте class MyTreeSet<E>, который реализует интерфейс Set<E> и работает на
основе отсортированного массива (любым способом) БЕЗ использования других
классов СТАНДАРТНОЙ БИБЛИОТЕКИ

Метод toString() должен выводить элементы в порядке их возрастания Формат
вывода: скобки (квадратные) и разделитель (запятая с пробелом) должны быть
такими же как в методе toString() обычной коллекции

Обязательные к реализации методы::
. toString()
. size()
. clear()
. isEmpty()
. add(Object)
. remove(Object)
. contains(Object)
. containsAll(Collection)
. addAll(Collection)
. removeAll(Collection)
. retainAll(Collection)
