= Лабораторная работа 11

== Задание на уровень А

.Создайте класс GraphA в методе main которого считывается строка структуры орграфа вида
. 0 -> 2
. 1 -> 3
. 2 -> 3
. 0 -> 1

.Затем в консоль выводится его топологическая сортировка вида
----
0 1 2 3
----

P.S. При равнозначности вершин их порядок вывода - лексикографический (т.е. по
алфавиту)

Дополните тесты СВОИМИ более сложными примерами и проверьте их
работоспособность.

Параметр метода run - это ввод. Параметр метода include - это вывод. Общее число
примеров должно быть не менее 20 (сейчас их 8).

== Задание на уровень B

.Создайте класс GraphB в методе main которого считывается строка структуры орграфа вида
. 1 -> 2
. 1 -> 3
. 2 -> 3

Затем в консоль выводится фраза о наличии циклов. Возможные варианты yes и no.

.Для указанного примера будет такой вывод
----
no
----

Дополните тесты СВОИМИ более сложными примерами и проверьте их
работоспособность.

Параметр метода run - это ввод. Параметр метода include - это вывод. Общее число
примеров должно быть не менее 12 (сейчас их 3).

== Задание на уровень C

.Создайте класс GraphC в методе main которого считывается строка структуры орграфа вида
. C -> B
. C -> I
. I -> A
. A -> D
. D -> I
. D -> B
. B -> H
. H -> D
. D -> E
. H -> E
. E -> G
. A -> F
. G -> F
. F -> K
. K -> G

Затем в консоль выводятся вершины компонент сильной связности каждый компонент с
новой строки, первый - исток, последний - сток, пробелов и табуляции в выводе
нигде нет.

.Пример для введенного выше графа
----
C
ABDHI
E
FGK
----

P.S. При равнозначности вершин в компоненте порядок их вывода -
лексикографический (т.е. по алфавиту)

Дополните тесты СВОИМИ более сложными примерами и проверьте их
работоспособность.

Параметр метода run - это ввод. Параметр метода include - это вывод. Общее число
примеров должно быть не менее 8 (сейчас их 2).
