= Лабораторная работа 14

== Задание на уровень A

=== Описание задачи

Создайте класс PointsA с методом main.

Пусть у нас есть набор точек в трехмерном пространстве, и мы хотим разбить их на
кластеры на основе расстояний между ними.

Используем структуру данных DSU с эвристикой по рангу или размеру поддерева для
объединения близких точек в один кластер.

С консоли вводится допустимое расстояние D между точками НЕ ВКЛЮЧИТЕЛЬНО [0,D) и
число точек N, а затем в каждой новой строке вводится точка с координатами X Y Z
через пробел.

Точки объединяются в DSU если расстояние между ними допустимо. Нужно вывести на
консоль число точек в полученных кластерах (в порядке возрастания).

=== Пример

Ввод:
....
2 8
1 1 1
9 9 9
1 2 2
9 8 9
3 2 3
3 4 4
8 8 9
5 6 5
....

Вывод:
....
3 5
....

== Задание на уровень B

=== Описание задачи

Создайте класс SitesB с методом main.

Пусть у нас есть набор связанных через взаимные гиперссылки сайтов, и мы хотим
разбить их на кластеры в которых можно по ссылкам дойти до любого сайта этого
кластера.

Цель: объединение связанных сайтов в кластеры.

Для кластеризации используем структуру данных DSU, причем эвристик должно быть
две:

. по рангу или размеру поддерева
. по сокращению пути поддерева

С консоли вводится в каждой новой строке пара связанных сайтов. Допускается
связь сайта с самим собой. Направление ссылок для простоты не учитывается. Пара
объединяется символом "+", а весь ввод завершается строкой "end" Нужно вывести
на консоль число сайтов в полученных кластерах (в порядке возрастания).
Сложность DSU должна быть не выше, чем N log*(N), где log*(N) - итерированный
логарифм.

=== Пример

Ввод:
....
java.mobile+science.org
test.ru+application.info
hello.info+world.org
hello.mobile+java.mobile
course.mobile+computer.net
application.org+application.net
application.info+test.app
application.org+hello.mobile
course.io+test.io
computer.app+course.com
end
....

Вывод:
....
5 3 2 2 2 2
....

Объяснение:
....
Группа (5): [application.org, java.mobile, science.org, hello.mobile, application.net]
Группа (3): [test.app, application.info, test.ru]
Группа (2): [hello.info, world.org]
Группа (2): [computer.net, course.mobile]
Группа (2): [test.io, course.io]
Группа (2): [computer.app, course.com]
....

== Задание на уровень C

=== Описание задачи

Создайте класс StatesHanoiTowerC с методом main.

Самостоятельно или с помощью интернета, или с помощью ботов типа ChatGPT найдите
и реализуйте решение задачи "Ханойские башни":

Даны три стержня A B C, на один из которых нанизаны N колец, причём кольца
отличаются размером и лежат меньшее на большем. Задача состоит в том, чтобы
перенести пирамиду из N колец за наименьшее число ходов на другой стержень. За
один раз разрешается переносить только одно кольцо, причём нельзя класть большее
кольцо на меньшее.

В методе main вводится высота N стартовой пирамиды А. Переместить кольца нужно
на пустую пирамиду B. В задаче есть еще одна пустая пирамида С.

Сгруппируйте с помощью DSU в поддеревья все те шаги решения задачи у которых
одинаковая наибольшая высота пирамид A B C. Стартовое состояние учитывать не
нужно.

Выведите на консоль размеры получившихся поддеревьев в порядке возрастания.
Коллекциями пользоваться нельзя!

Эвристики DSU:
. по размеру поддерева
. по сокращению пути поддерева

=== Пример

Ввод:
....
5
....

Вывод:
....
1 4 8 18
....

Шаги решения:

.Стартовое состояние (не учитывается)
....
A: [5, 4, 3, 2, 1]
B: []
C: []
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: [5, 4, 3, 2]
B: [1]
C: []
....

.Перемещаем диск 2 со стержня A на стержень C
....
A: [5, 4, 3]
B: [1]
C: [2]
....

.Перемещаем диск 1 со стержня B на стержень C
....
A: [5, 4, 3]
B: []
C: [2, 1]
....

.Перемещаем диск 3 со стержня A на стержень B
....
A: [5, 4]
B: [3]
C: [2, 1]
....

.Перемещаем диск 1 со стержня C на стержень A
....
A: [5, 4, 1]
B: [3]
C: [2]
....

.Перемещаем диск 2 со стержня C на стержень B
....
A: [5, 4, 1]
B: [3, 2]
C: []
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: [5, 4]
B: [3, 2, 1]
C: []
....

.Перемещаем диск 4 со стержня A на стержень C
....
A: [5]
B: [3, 2, 1]
C: [4]
....

.Перемещаем диск 1 со стержня B на стержень C
....
A: [5]
B: [3, 2]
C: [4, 1]
....

.Перемещаем диск 2 со стержня B на стержень A
....
A: [5, 2]
B: [3]
C: [4, 1]
....

.Перемещаем диск 1 со стержня C на стержень A
....
A: [5, 2, 1]
B: [3]
C: [4]
....

.Перемещаем диск 3 со стержня B на стержень C
....
A: [5, 2, 1]
B: []
C: [4, 3]
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: [5, 2]
B: [1]
C: [4, 3]
....

.Перемещаем диск 2 со стержня A на стержень C
....
A: [5]
B: [1]
C: [4, 3, 2]
....

.Перемещаем диск 1 со стержня B на стержень C
....
A: [5]
B: []
C: [4, 3, 2, 1]
....

.Перемещаем диск 5 со стержня A на стержень B
....
A: []
B: [5]
C: [4, 3, 2, 1]
....

.Перемещаем диск 1 со стержня C на стержень A
....
A: [1]
B: [5]
C: [4, 3, 2]
....

.Перемещаем диск 2 со стержня C на стержень B
....
A: [1]
B: [5, 2]
C: [4, 3]
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: []
B: [5, 2, 1]
C: [4, 3]
....

.Перемещаем диск 3 со стержня C на стержень A
....
A: [3]
B: [5, 2, 1]
C: [4]
....

.Перемещаем диск 1 со стержня B на стержень C
....
A: [3]
B: [5, 2]
C: [4, 1]
....

.Перемещаем диск 2 со стержня B на стержень A
....
A: [3, 2]
B: [5]
C: [4, 1]
....

.Перемещаем диск 1 со стержня C на стержень A
....
A: [3, 2, 1]
B: [5]
C: [4]
....

.Перемещаем диск 4 со стержня C на стержень B
....
A: [3, 2, 1]
B: [5, 4]
C: []
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: [3, 2]
B: [5, 4, 1]
C: []
....

.Перемещаем диск 2 со стержня A на стержень C
....
A: [3]
B: [5, 4, 1]
C: [2]
....

.Перемещаем диск 1 со стержня B на стержень C
....
A: [3]
B: [5, 4]
C: [2, 1]
....

.Перемещаем диск 3 со стержня A на стержень B
....
A: []
B: [5, 4, 3]
C: [2, 1]
....

.Перемещаем диск 1 со стержня C на стержень A
....
A: [1]
B: [5, 4, 3]
C: [2]
....

.Перемещаем диск 2 со стержня C на стержень B
....
A: [1]
B: [5, 4, 3, 2]
C: []
....

.Перемещаем диск 1 со стержня A на стержень B
....
A: []
B: [5, 4, 3, 2, 1]
C: []
....
